# YAML settings for the app
appconfig: &DEFAULT
  work_dir: ./
  log_dir: logs/
  data_dir: data/raw/
  model_dir: models/
  script_dir: scripts/
  report_dir: reports/
  log_format: '%(asctime)s:%(filename)s:%(funcName)s:[%(levelname)s] %(message)s'
